from twilio.rest import Client
from credentials import account_sid, auth_token, my_cell, my_twilio

client = Client(account_sid, auth_token)

my_msg = "Good evening y'all. This message was generated by a Python script. How neat is that?"

message = client.messages.create(to=my_cell, from_=my_twilio, body= my_msg)